### PR TITLE
TM1637 support

### PR DESCRIPTION
**Pull request by Mynasru**
## Description:
Added support for the 4*7-segment driver TM1637.
Ported from https://github.com/avishorp/TM1637

**Related issue (if applicable):** [issue](https://github.com/esphome/feature-requests/issues/20)
**Pull request in [esphome](https://github.com/esphome/esphome) with python changes (if applicable):** esphome/esphome#<esphome PR number goes here>
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:

  - [ ] The code change is tested and works locally.
  - [X] The code change follows the [standards](https://esphome.io/guides/contributing.html#contributing-to-esphome-core)

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by OttoWinter** [comment]
Hi! Thanks for this PR, unfortunately the ESPHome codebase has changed a bit, all code now resides in https://github.com/esphome/esphome.

**Comment by Mynasru** [comment]
I'll PR again 👍

**Comment by Bierchermuesli** [comment]
waited for this! :-) Thanks!

**Comment by hildwin** [comment]
I have several TM1637-displays and I'm really looking forward to integrating them. Please make it so! :)

**Comment by brandond** [comment]
As noted above, all work has moved to https://github.com/esphome/esphome.

**Pull request closed without merging**
