### PR TITLE
Add display pages abstraction

### PR DESCRIPTION
**Pull request by OttoWinter**
## Description:

**Related issue (if applicable):** fixes <link to issue>

**Pull request in [esphome](https://github.com/esphome/esphome) with python changes (if applicable):** esphome/esphome#<esphome PR number goes here>
**Pull request in [esphome-docs](https://github.com/esphome/esphome-docs) with documentation (if applicable):** esphome/esphome-docs#<esphome-docs PR number goes here>

## Checklist:

  - [ ] The code change is tested and works locally.
  - [ ] The code change follows the [standards](https://esphome.io/guides/contributing.html#contributing-to-esphome-core)

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by HFsi** [comment]
Any advance on what this is going to be?

**Comment by OttoWinter** [comment]
@HFsi You will be able to write something like this https://github.com/esphome/esphome/pull/435/files#diff-44dab94e1bdc2ffd256872ffad5c6970R1028 - basically you can use multiple pages on the display and switch between them with actions

**Comment by HFsi** [comment]
That´ll be way usefull!
Thanks

**Comment by davericher** [comment]
You have read my mind again :D

**Pull request merged**
