### PR TITLE
Print debug info from the debug component on API connect.

### PR DESCRIPTION
**Pull request by placidorevilla**
## Description:

Dump debug information on API connection (very similar to the way it dumps config).

## Checklist:

  - [x] The code change is tested and works locally.
  - [x] The code change follows the [standards](https://esphome.io/guides/contributing.html#contributing-to-esphome-core)

If user exposed functionality or configuration variables are added/changed:
  - [ ] Documentation added/updated in [esphome-docs](https://github.com/esphome/esphome-docs).

### CODE REVIEW

**Comment by placidorevilla** [comment]
This is how it looks:

```
$ esphome test.yaml logs
INFO Reading configuration...
...
[00:25:08][I][application:098]: esphome-core version 1.11.2 compiled on Mar 19 2019, 00:00:18
[00:25:08][D][debug:029]: ESPHome Core version 1.11.2
[00:25:08][D][debug:031]: Free Heap Size: 32592 bytes
[00:25:08][D][debug:048]: Flash Chip: Size=4096kB Speed=40MHz Mode=DOUT
[00:25:08][D][debug:126]: Chip ID: 0x0031CF88
[00:25:08][D][debug:127]: SDK Version: 2.2.1(cfd48f3)
[00:25:08][D][debug:128]: Core Version: 2_4_2
[00:25:08][D][debug:129]: Boot Version=31 Mode=1
[00:25:08][D][debug:130]: CPU Frequency: 80
[00:25:08][D][debug:131]: Flash Chip ID=0x00164020
[00:25:08][D][debug:132]: Reset Reason: Software/System restart
[00:25:08][D][debug:133]: Reset Info: Fatal exception:0 flag:4 (SOFT_RESTART) epc1:0x00000000 epc2:0x00000000 epc3:0x00000000 excvaddr:0x00000000 depc:0x00000000
[00:25:08][C][status_led:023]: Status LED:
[00:25:08][C][status_led:024]:   Pin: GPIO2 (Mode: OUTPUT)
...
```

**Review by OttoWinter — COMMENTED** [review]
Instead of doing all this, move the debug print into a overloaded `dump_config` call like all other components. The core will call it.

**Comment by placidorevilla** [comment]
I've updated the PR to use dump_config.

**Review by OttoWinter — COMMENTED** [review]
Great! Thanks!

**Pull request merged**
